add support for Travis/macOS with xcode9.3 image
* add Travis tests for xcode9.3. `osx_image` does not expand the build matrix: https://github.com/travis-ci/travis-ci/issues/7587
  so we have to specify it manually, thanks to @mxcl for the trick: https://github.com/travis-ci/travis-ci/issues/7587#issuecomment-330700855

* rabbitmq: fix on Travis/macOS xcode9.3

rabbitmq fails to install on Travis/macOS xcode9.3 image by default with error:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink sbin/cuttlefish
/usr/local/sbin is not writable.
```

This seems to be a general problem of Homebrew with macOS High Sierra, since it does not have /usr/local/sbin created by default.

We create now /usr/local/sbin beforehand to avoid the error.